### ISSUE TITLE
Pagination Component Page number > 100 gets ellipsed for small window-width(e.g. Ticket Sidebar)

### ISSUE THREAD

**Issue by karunkamal** [zendeskgarden/website#269]
Note: Raised an issue here hoping we can push a Note on Pagination Component If this is expected behavior

Take a look at this [CodeSandbox](https://codesandbox.io/s/elegant-butterfly-vk1zo?file=/src/Example.tsx)

## Expectation

Shouldn't get ellipsed Page numbers.

## Reality

The  3-digit Page numbers are getting ellipsed if window-width is small and `Pagination`'s prop `pagePadding > 0`

## Steps to Reproduce

1. Visit [here](https://vk1zo.csb.app/)
1. Reduce the window width around 320px
1. Notice Case 2, 3

### Fine Print

- URL: [Pagination](https://garden.zendesk.com/components/pagination)
- Version: ^8.x
- Browsers: all

**Comment by jzempel** [comment]
@karunkamal thanks for the detailed breakdown with demo links. As it turns out, the pages are rendering as designed. I realize that this makes them nearly impossible to differentiate in the case you're showing. However, this is the desired approach for ensuring that the component doesn't break UI by wrapping or extending beyond the boundaries of the block. I think you have a couple of options:
- Set up the `pagePadding` prop to dynamically respond to the size of the page, so that you drop to `pagePadding=0` when the width drops down to ~320px
- If you don't prefer our styling choices, use `ThemeProvider` [targeting](https://garden.zendesk.com/components/theme-provider#targeting) to make the desired overrides. In this case, reaching into the `pagination.page` component and overriding `text-overflow`, etc
- Use some variation of [cursor pagination](https://garden.zendesk.com/components/pagination#cursor-pagination) (with maybe just `CursorPagination.Previous` and `CursorPagination.Next`?)
